export const people = ['Aghajany Haji Saeid','Biegalski Jerzy','Bogusławski Paweł','Bosy Jarosław','Bury Grzegorz','Cegła Adam','Ćmielewski Kazimierz',
'Dach Wojciech','Drożdżewski Mateusz','Dziwoska Teresa','Gałdyn Filip','Gołuch Piotr','Hadaś Edyta','Hadaś Tomasz','Hordyniec Barbara',
'Hordyniec Paweł','Ilieva Maya','Iwaniak Adam','Jamroz Olgierd','Jarząbek-Rychard Małgorzata','Jóźków Grzegorz','Kaczmarek Adrian','Kaplon Jan',
'Karpina Mateusz','Kaźmierski Kamil','Kontny Bernard','Kuchmister Janusz','Marut Grzegorz','Mehdi Saqib','Michalski Adam','Mikos Marcin',
'Najder Joanna','Owczarek-Wesołowska Magdalena','Pawłuszek-Filipiak Kamila','Piotrowicz Michał','Porucznik Sylwia','Rohm Witold','Sierny Jan',
'Smolak Kamil','Sośnica Krzysztof','Sowa Wojciech','Stasch Krzysztof','Strugarek Dariusz','Tondas Damian','Trojanowicz Marek','Trzcina Estera',
'Tymków Przemysław','Walicka Agata','Wielgocka Natalia','Wilczyńska Izabela','Zajdel Radosław','Żukowski Wiktor'];

export const rooms = ['01-Serwerownia', '02-Laboratorium', '03-Laboratorium', '04-Magazyn sprzętu geodezyjnego-Wiktor Żukowski', '05-Laboratorium', '06-Magazyn', 
'07-Toaleta', '021a-Węzeł cieplny', '021b-Pomieszczenie gospodarcze', '022-Warsztat naprawy sprzętów geodezyjnych-Wiktor Żukowski', 
'023-Gabinet SKN Geodetów', '024-Magazyn', '025-Magazyn', '1-Gabinet-dr hab. inż. Marek Trojanowicz, prof. UPWr', '2-Serwerownia', 
'3-Laboratorium', '4-Pokój gospodarczy', '5-Toaleta męska', '6-Toaleta damska', '22-Gabinet', '23-Gabinet-dr hab. inż. Piotr Gołuch, prof. UPWr', 
'24-Gabinet-dr hab. Kazimierz Ćmielewski, dr inż. Janusz Kuchmister', '25a-Gabinet-dr inż. Izabela Wilczyńska, mgr inż. Wojciech Sowa', 
'25-Gabinet-mgr inż. Mateusz Karpina', '100-Biblioteka IGIG', '101-Serwerownia/Gabinet-mgr inż. Jan Sierny, mgr inż. Magdalena Owczarek-Wesołowska', 
'102-Sala dydaktyczna', '103-Toaleta męska', '104-Toaleta damska', '121-Gabinet-Saqib Mehdi, dr Saeid Haji Aghajany', 
'122-Gabinet-dr inż. Sylwia Porucznik, dr inż. Teresa Dzikowska', '123-Gabinet-mgr inż. Adam Cegła, mgr inż. Damian Tondas', 
'124-Gabinet-mgr inż. Estera Trzcina, mgr inż. Barbara Hordyniec', '125-Gabinet-dr inż. Kamil Smolak, dr inż. Pawel Hordyniec', 
'126-Gabinet-mgr inż. Wojciech Dach', '126a-Gabinet-prof. dr hab. inż. Witold Rohm', '127-Gabinet', '200a-Gabinet-dr inż. Paweł Bogusławski', 
'200b-Gabinet-dr hab. inż. Adam Iwaniak', '200c-Gabinet-dr hab. inż. Grzegorz Jóźków prof. UPWr, dr inż. Przemysóaw Tymków', 
'201-Pomieszczenie socjalne', '202-Sala dydaktyczna', '203-Toaleta męska', '204-Toaleta damska', '219-Gabinet-prof. dr hab. inż. Bernard Kontny', 
'220-Gabinet-dr inż. Olgierd Jamroz, mgr inż. Michał Piotrowicz, mgr inż. Jerzy Biegalski', '221-Gabinet-dr inż. Adam Michalski', 
'222-Gabinet-dr inż. Edyta Hadaś, dr inż. Agata Walicka', '223-Gabinet-dr inż. Maya Ilieva', 
'224-Gabinet-dr inż. Malgorzata Jarząbek-Rychard, dr inż. Kamila Pawłuszek-Filipak', '225-Gabinet-mgr inż. Natalia Wielgocka, mgr inż. Krzysztof Stasch', 
'226-Stacja GPS', '300-Gabinet-dr hab. inż. Jan Kapłon, prof. UPWr', '301-Gabinet-prof. dr hab. inż. Krzysztof Sośnica', 
'302-Gabinet-dr hab. inż. Tomasz Hadaś, prof. UPWr', '303-Gabinet-prof. dr hab. inż. Jarosław Bosy', '304-Sala seminaryjna', 
'305-Gabinet (katedra matematyki)', '306-Toaleta damska', '307-Toaleta męska', '324-Gabinet-dr inż. Adrian Kaczmarek, dr inż. Mateusz Drożdżewski', 
'325-Gabinet-mgr inż. Marcin Mikos, mgr inż. Filip Gałdyn', '326-Gabinet-dr inż. Kamil Kaźmierski, mgr inż. Grzegorz Marut', 
'327-Gabinet-mgr inż. Joanna Najder, dr inż.  Grzegorz Bury', '328-Gabinet-dr inż. Radosław Zajdel, dr inż. Dariusz Strugarek', 
'329-Kuchnia', '329a-Sala Konferencyjna', '330-Magazyn', '400a-Gabinet', '400b-Gabinet', '401-Gabinet', '402a-Gabinet', '402b-Gabinet', 
'403-Sala dydaktyczna', '404-Toaleta męska', '405-Toaleta damska', '418-Gabinet', '419-Gabinet', '420-Gabinet', '421-Gabinet', '422-Gabinet', 
'423-Gabinet', '424-Gabinet', '425-Gabinet'];
