export const people = ['Aghajany Haji Saeid','Biegalski Jerzy','Bogusławski Paweł','Bosy Jarosław','Bury Grzegorz','Cegła Adam','Ćmielewski Kazimierz',
'Dach Wojciech','Drożdżewski Mateusz','Dziwoska Teresa','Gałdyń Filip','Gołuch Piotr','Hadaś Edyta','Hadaś Tomasz','Hordyniec Barbara',
'Hordyniec Paweł','Ilieva Maya','Iwaniak Adam','Jamroz Olgierd','Jarząbek-Rychard Małgorzata','Jóźków Grzegorz','Kaczmarek Adrian','Kaplon Jan',
'Karpina Mateusz','Kaźmierski Kamil','Kontny Bernard','Kuchmister Janusz','Marut Grzegorz','Mehdi Saqib','Michalski Adam','Mikos Marcin',
'Najder Joanna','Owczarek-Wesołowska Magdalena','Pawłuszek-Filipiak Kamila','Piotrowicz Michał','Porucznik Sylwia','Rohm Witold','Sierny Jan',
'Smolak Kamil','Sośnica Krzysztof','Sowa Wojciech','Stasch Krzysztof','Strugarek Dariusz','Tondas Damian','Trojanowicz Marek','Trzcina Estera',
'Tymków Przemysław','Walicka Agata','Wielgocka Natalia','Wilczyńska Izabela','Zajdel Radosław','Żukowski Wiktor'];

export const rooms = ['01-Serwerownia', '02-Laboratorium', '03-Laboratorium', '04-Magazyn sprzętu geodezyjnego-Wiktor Żukowski', '05-Laboratorium', '06-Magazyn', 
'07-Toaleta', '021a-Węzeł cieplny', '021b-Pomieszczenie gospodarcze', '022-Warsztat naprawy sprzętów geodezyjnych-Wiktor Żukowski', 
'023-Gabinet SKN Geodetów', '024-Magazyn', '025-Magazyn', '1-Gabinet-dr hab. inz. Marek Trojanowicz, prof. UPWr', '2-Serwerownia', 
'3-Laboratorium', '4-Pokój gospodarczy', '5-Toaleta męska', '6-Toaleta damska', '22-Gabinet', '23-Gabinet-dr hab. Inz. Piotr Goluch, prof. UPWr', 
'24-Gabinet-dr hab. Kazimierz Cmielewski, dr inz. Janusz Kuchmister', '25a-Gabinet-dr inz. Izabela WilczyÄska, mgr inz. Wojciech Sowa', 
'25-Gabinet-mgr inz. Mateusz Karpina', '100-Biblioteka IGIG', '101-Serwerownia/Gabinet-mgr inz. Jan Sierny, mgr inz. Magdalena Owczarek-Wesolowska', 
'102-Sala dydaktyczna', '103-Toaleta meska', '104-Toaleta damska', '121-Gabinet-Saqib Mehdi, dr Saeid Haji Aghajany', 
'122-Gabinet-dr inz. Sylwia Porucznik, dr inz. Teresa Dzikowska', '123-Gabinet-mgr inz. Adam Cegla, mgr inz. Damian Tondas', 
'124-Gabinet-mgr inz. Estera Trzcina, mgr inz. Barbara Hordyniec', '125-Gabinet-dr inz. Kamil Smolak, dr inz. Pawel Hordyniec', 
'126-Gabinet-mgr inz. Wojciech Dach', '126a-Gabinet-prof. dr hab. inz. Witold Rohm', '127-Gabinet', '200a-Gabinet-dr inz. Pawel Boguslawski', 
'200b-Gabinet-dr hab. inz. Adam Iwaniak', '200c-Gabinet-dr hab. inz. Grzegorz Jozkow prof. UPWr, dr inz. Przemyslaw Tymkow', 
'201-Pomieszczenie socjalne', '202-Sala dydaktyczna', '203-Toaleta meska', '204-Toaleta damska', '219-Gabinet-prof. dr hab. inz. Bernard Kontny', 
'220-Gabinet-dr inz. Olgierd Jamroz, mgr inz. Michal Piotrowicz, mgr inz. Jerzy Biegalski', '221-Gabinet-dr inz. Adam Michalski', 
'222-Gabinet-dr inz. Edyta Hadas, dr inz. Agata Walicka', '223-Gabinet-dr inz. Maya Ilieva', 
'224-Gabinet-dr inz. Malgorzata Jarzbek-Rychard, dr inz. Kamila Pawluszek-Filipak', '225-Gabinet-mgr inz. Natalia Wielgocka, mgr inz. Krzysztof Stasch', 
'226-Stacja GPS', '300-Gabinet-dr hab. inz. Jan Kaplon, prof. UPWr', '301-Gabinet-prof. dr hab. inz. Krzysztof Sosnica', 
'302-Gabinet-dr hab. inz. Tomasz Hadas, prof. UPWr', '303-Gabinet-prof. dr hab.. Inz. Jaroslaw Bosy', '304-Sala seminaryjna', 
'305-Gabinet (katedra matematyki)', '306-Toaleta damska', '307-Toaleta meska', '324-Gabinet-dr inz. Adrian Kaczmarek, dr inz. Mateusz Drozdzewski', 
'325-Gabinet-mgr inz. Marcin Mikos, mgr inz. Filip Galdyn', '326-Gabinet-dr inz. Kamil Kazmierski, mgr inz. Grzegorz Marut', 
'327-Gabinet-mgr inz. Joanna Najder, dr inz.  Grzegorz Bury', '328-Gabinet-dr inz. Radoslaw Zajdel, dr inz. Dariusz Strugarek', 
'329-Kuchnia', '329a-Sala Konferencyjna', '330-Magazyn', '400a-Gabinet', '400b-Gabinet', '401-Gabinet', '402a-Gabinet', '402b-Gabinet', 
'403-Sala dydaktyczna', '404-Toaleta meska', '405-Toaleta damska', '418-Gabinet', '419-Gabinet', '420-Gabinet', '421-Gabinet', '422-Gabinet', 
'423-Gabinet', '424-Gabinet', '425-Gabinet'];
